# curl --location --request POST 'http://localhost:8080/auth/realms/abamais/protocol/openid-connect/token'
#--header 'Content-Type: application/x-www-form-urlencoded'
#--data-urlencode 'grant_type=password'
#--data-urlencode 'username=kelvin'
#--data-urlencode 'password=123456'
#--data-urlencode 'scope=abamais'
#--data-urlencode 'client_id=abamais-empresa-x'
#--data-urlencode 'client_secret=32e4fa8e-f936-4162-a109-c8a62046e055'
POST http://localhost:8080/auth/realms/abamais/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=kelvin&password=123456&scope=abamais&client_id=abamais-empresa-x&client_secret=32e4fa8e-f936-4162-a109-c8a62046e055

###

# curl --location --request GET 'http://localhost:9000/v1/hello'
#--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItcnJaSGUtdDdPQUZGZVRMZ3pNNWxUWEl5YU1MaXJvMUYxcnBYSWZ2VFhvIn0.eyJleHAiOjE2MjE2MTk2MzMsImlhdCI6MTYyMTYxOTMzMywianRpIjoiMDMwYTdjYjktM2I4NC00NzNjLTg0OWUtNTc0ODdiNWM5MmFhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2FiYW1haXMiLCJzdWIiOiJlMWQ1MWRhZi05NjYwLTQwYjQtYTU4Yi0zZWI3MTk2YzZiZTQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhYmFtYWlzLWVtcHJlc2EteCIsInNlc3Npb25fc3RhdGUiOiIxMzg4NDI4OS02NDVkLTRjYzgtODUxYi00YmQ2NDFkY2M0ZGIiLCJhY3IiOiIxIiwic2NvcGUiOiJhYmFtYWlzIiwicm9sZXMiOlsiQ1VTVE9NRVIiLCJBRE1JTiJdfQ.SUhe0SJCKHe9SFhkloh-RrmtpTU5gACBXFTMRwvImpWXla8-hsRqqZsbHyBFWmgKA5A-089UGYZhQLK6uM6ExEhX2PhmDoYBUjvXDag8iI4D5GTVTI8vr_CjjN7uVQVuSaj7MwLcwc-5X6W77CjpnhCM_Hcp1IIZsjZRE66DjK3jgoxFQuTAVclIDyfCS5Cdo94SJlROOD7k7Bkgx1MqhP_bNatmTd4pmBr6gK9hM68J19X6ZJZdRjOA3Oxzimxg0u5oDWcg5ZXmBXRCGX1CbicyuDbB8sfp3IPk59CrP6nVrRMVT_bb9ZclB976MNqo0Lfh9u7WsO9jRank46AKgw'
#--header 'Cookie: JSESSIONID=bCtCegqWd-42gmnm7QYwzItTikuCzOgFXHBtzJLu'
GET http://localhost:9000/v1/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICItcnJaSGUtdDdPQUZGZVRMZ3pNNWxUWEl5YU1MaXJvMUYxcnBYSWZ2VFhvIn0.eyJleHAiOjE2MjE2MjE2NjIsImlhdCI6MTYyMTYyMTM2MiwianRpIjoiNjRkZThhYTUtYzFkOC00M2M5LTlkNTEtNDcyNThkN2NiZGU0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL2FiYW1haXMiLCJzdWIiOiJlMWQ1MWRhZi05NjYwLTQwYjQtYTU4Yi0zZWI3MTk2YzZiZTQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhYmFtYWlzLWVtcHJlc2EteCIsInNlc3Npb25fc3RhdGUiOiI5M2E1MWIwZC0xODQwLTQ4YWYtYWViMi1kZTBkNDE3YmE2YzgiLCJhY3IiOiIxIiwic2NvcGUiOiJhYmFtYWlzIiwiYXV0aG9yaXRpZXMiOlsiQ1VTVE9NRVIiLCJBRE1JTiIsIlVTRVIiXX0.AgMb18BS2MA3vFnmNXQUHXB0qJoL3T-TCbk3OWMuI-8fLBEDnOftcwG7N6niqXBN69miEhq5zDm6-gzxhMT0Y6JW9L1e0VhVpVR8yMGwQJQ03KRPiT6BdFfXfkiEtYOmOiPPztrPgsiX_z2byl7p04GY4HWhX8cUhMP75ex-J9cFKPtlidqGDq2SlUUouMYfAt21DL3mxdxlm3l6HWrkbi_6GChjLckh2eP8MV2lN1tZTx73ZCCvVN37-fiWYJwPdNCVC92Xo5ttOJzCcRzxZI4nA5LqUQZod3AI_FN0jZw4q3xG8dgZCLHB2FlgRvX2dIV22T6kUGICtBqyfvDbkg

###